# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Brand.create!(
  [
{brand_name: "A.LANGE&SOHNE", brand_kana: " ランゲ&ゾーネ"},
{brand_name: "APPLE", brand_kana: "アップル"},
{brand_name: "AUDEMARS PIGUET", brand_kana: "オーデマ・ピゲ"},
{brand_name: "BULOVA", brand_kana: "ブローバ"},
{brand_name: "BAUME&MERCIER", brand_kana: "ボーメ&メルシエ"},
{brand_name: "Bell&Ross", brand_kana: "ベルアンドロス"},
{brand_name: "BURBERRY", brand_kana: "バーバリー"},
{brand_name: "BLANCPAIN", brand_kana: "ブランパン"},
{brand_name: "Breguet", brand_kana: "ブレゲ"},
{brand_name: "BREITLING", brand_kana: "ブライトリング"},
{brand_name: "BULOVA", brand_kana: "ブローバ"},
{brand_name: "BVLGARI", brand_kana: "ブルガリ"},
{brand_name: "CAMPANOLA", brand_kana: "カンパノラ"},
{brand_name: "CARL F. BUCHERER", brand_kana: "カール・エフ・ブヘラ"},
{brand_name: "Carl von Zeyten", brand_kana: "カール・フォン・ツォイテン"},
{brand_name: "Cartier", brand_kana: "カルティエ"},
{brand_name: "Casio", brand_kana: "カシオ"},
{brand_name: "CHANEL", brand_kana: "シャネル"},
{brand_name: "CITIZEN", brand_kana: "シチズン"},
{brand_name: "Daniel Wellington", brand_kana: "ダニエル・ウェリントン"},
{brand_name: "EDOX", brand_kana: "エドックス"},
{brand_name: "FRANCK MULLER", brand_kana: "フランクミュラー"},
{brand_name: "FREDERIQUE CONSTANT", brand_kana: "フレデリック・コンスタント"},
{brand_name: "G-SHOCK", brand_kana: "ジーショック"},
{brand_name: "GaGà Milano", brand_kana: "ガガミラノ"},
{brand_name: "GIRARD-PERREGAUX", brand_kana: "ジラール・ペルゴ"},
{brand_name: "H.Moser & Cie.", brand_kana: "Ｈモーサー"},
{brand_name: "HAMILTON", brand_kana: "ハミルトン"},
{brand_name: "HERMÈS", brand_kana: "エルメス"},
{brand_name: "HUBLOT", brand_kana: "ウブロ"},
{brand_name: "Ice-Watch", brand_kana: "アイスウォッチ"},
{brand_name: "IKEPOD", brand_kana: "アイクポッド"},
{brand_name: "IWC", brand_kana: "アイダブリューシー"},
{brand_name: "Jaeger-LeCoultre", brand_kana: "ジャガー・ルクルト"},
{brand_name: "Knot", brand_kana: "ノット"},
{brand_name: "LONGINES", brand_kana: "ロンジン"},
{brand_name: "LOUIS VUITTON", brand_kana: "ルイビィトン"},
{brand_name: "LUMI-NOX", brand_kana: "ルミノックス"},
{brand_name: "MONDAINE", brand_kana: "モンディーン"},
{brand_name: "MONTBLANC", brand_kana: "モンブラン"},
{brand_name: "MOVADO", brand_kana: "モバード"},
{brand_name: "NIXON", brand_kana: "ニクソン"},
{brand_name: "NOMOS", brand_kana: "ノモス"},
{brand_name: "OFFICINE PANERAI", brand_kana: "パネライ"},
{brand_name: "OMEGA", brand_kana: "オメガ"},
{brand_name: "ORIENT", brand_kana: "オリエント"},
{brand_name: "Patek Philippe", brand_kana: "パテック・フィリップ"},
{brand_name: "Paul Smith", brand_kana: "ポール・スミス"},
{brand_name: "Piaget", brand_kana: "ピアジェ"},
{brand_name: "PORSCHE DESIGN", brand_kana: "ポルシェ・デザイン"},
{brand_name: "PRO TREK", brand_kana: "プロトレック"},
{brand_name: "ROGER DUBUIS", brand_kana: "ロジェ・デュブイ"},
{brand_name: "ROLEX", brand_kana: "ロレックス"},
{brand_name: "SEIKO", brand_kana: "セイコー"},
{brand_name: "SINN", brand_kana: "ジン"},
{brand_name: "SKAGEN", brand_kana: "スカーゲン"},
{brand_name: "Swatch", brand_kana: "スウォッチ"},
{brand_name: "TAG Heuer", brand_kana: "タグホイヤー"},
{brand_name: "Tiffany & Co.", brand_kana: "ティファニー"},
{brand_name: "TIMEX", brand_kana: "タイメックス"},
{brand_name: "TISSOT", brand_kana: "ティソ"},
{brand_name: "TUDOR", brand_kana: "チューダー"},
{brand_name: "ULYSSE NARDIN", brand_kana: "ユリス・ナルダン"},
{brand_name: "VACHERON CONSTANTIN", brand_kana: "ヴァシュロン・コンスタンタン"},
{brand_name: "VERSACE", brand_kana: "ヴェルサーチ"},
{brand_name: "ZENITH", brand_kana: "ゼニス"}
]
)